### ISSUE TITLE
Implement parameters for users

### ISSUE THREAD

**Issue by avatousiou** [WGBH/stock_sales#13]
**Done when:**
Users have strong parameters through devise

**Comment by afred** [comment]
@avatousiou take care here not to duplicate functionality provided by Devise. Devise generates for us a  `RegistrationsController` for handling new registrations, a `SessionsController` for handling "log in", "log out", and "current user" functionality, a `PasswordsController` for forgotten passwords, and some others.

Can you be more specific about the need for a `UsersController`? Generally speaking, you would need one if you wanted to take data from a `User` model, and put it together on a `User`-specific page.

**Comment by avatousiou** [comment]
Split this up into two tickets: one for adding parameters and another for creating the user show page
