### ISSUE TITLE
Add email and phone number to the header

### ISSUE THREAD

**Issue by avatousiou** [WGBH/stock_sales#27]
**Done when:**
Email and phone number are present in the header like in Mike's mockups

**Comment by Muraszko-wgbh** [comment]
@avatousiou Also, in case you were wondering about the Glyphicons (shopping cart, profile person image) they can come from here:
http://www.w3schools.com/bootstrap/bootstrap_ref_comp_glyphs.asp
http://glyphicons.com
Which is what they used for the News site.  Not sure if you've seen this or not.

Make sure it's only the Halflings.
