### ISSUE TITLE
Fix blacklight style

### ISSUE THREAD

**Issue by avatousiou** [WGBH/stock_sales#57]
**Done when:**
Remove blacklight search bar from home page

![screen shot 2014-11-12 at 2 45 14 pm](https://cloud.githubusercontent.com/assets/8029317/5017288/a0a4e1ae-6a7a-11e4-9a00-fe28ce47cdf1.png)

**Comment by ursomniac** [comment]
Can I get removed from this?

**Comment by afred** [comment]
@ursomniac hi Bob, I think you are getting notifications because you are on the "Owners" team of WGBH's github account. You should be able to adjust your notification setting in github. I don't think we can do it for you.
