### ISSUE TITLE
Import style guide from news site

### ISSUE THREAD

**Issue by avatousiou** [WGBH/stock_sales#6]
- [x] Install bootstrap-sass
- [x] Install compass
- [x] Import style guide from http://bostonlocaltv.org/styleguide

**Comment by Muraszko-wgbh** [comment]
If you needed the URL its:
http://bostonlocaltv.org/styleguide

**Comment by avatousiou** [comment]
Closed by:
a3b7b66d26edbbf7b5601b2c36481cb289d543a7
