### ISSUE TITLE
Replace "Stock Sales Digital Library" in the header with the stock sales logo

### ISSUE THREAD

**Issue by avatousiou** [WGBH/stock_sales#62]

**Comment by Muraszko-wgbh** [comment]
@avatousiou 
Here's the layered .tiff file, see if that works:
smb://deptfs.wgbh.org/dept/MLA/Stock Sales (Anthony)/WGBH_Stock_Sales_LOGO_200.tif

**Comment by avatousiou** [comment]
Looks like it needs to be something other than .tiff

**Comment by Muraszko-wgbh** [comment]
@avatousiou 
No problem, would you please send me the color of the header, or a screen grab?  I'll just make a jpg with that color as the background.

**Comment by avatousiou** [comment]
The color is #3e444a and here's a picture:
![image](https://cloud.githubusercontent.com/assets/8029317/5281505/24029cd8-7acc-11e4-8f3e-3499161bb4d1.png)

**Comment by Muraszko-wgbh** [comment]
@avatousiou 
Here's the location of the PNG
smb://deptfs.wgbh.org/dept/MLA/Stock Sales (Anthony)/WGBH_Stock_Sales_logo_200.png

**Comment by avatousiou** [comment]
Should we increase the size of the banner so that the logo fits or decrease the size of the logo until it fits in the banner? Currently the height is 50px.

**Comment by Muraszko-wgbh** [comment]
@avatousiou 
I shrunk it to 45px high, find it here and see how it looks:
smb://deptfs.wgbh.org/dept/MLA/Stock Sales (Anthony)/WGBH_Stock_Sales_45px.png
